--liquibase formatted sql

-- Generated by scripts/generate-user-seed.ts — do not edit by hand.
--   --role COMMISSIONER --count 5 --district CM-1 --seed 20261003 --context dev
--
-- Accounts (national id / password commission1234):
--   7888165997564  สิปปกร แขนอก
--   8162104362606  สุชานาฎ เกิดนอก
--   8167438575289  พัชรนันท์ เกิดค้างพลู
--   3656506578750  สุรษิต เกตุสีสุก
--   5181599500094  มณทารัตน์ แขค้างพลู

--changeset election:902-seed-commissioners context:dev
INSERT INTO users (national_id, password_hash, first_name, last_name, address, district_id, role) VALUES
    ('7888165997564', 'scrypt$795b3127e6ef87f9804b601bc4d4b171$ea7d814c2f88bbfa3999313b286eb5bcc2b53caa894394be589672ccd56f7acfce736c59b52e6b874d9cc60b65e7fbcfa023a561ce562b4878bf7962a8589049', 'สิปปกร', 'แขนอก', '2659 อาจณรงค์', 'CM-1', 'COMMISSIONER'),
    ('8162104362606', 'scrypt$795b3127e6ef87f9804b601bc4d4b171$ea7d814c2f88bbfa3999313b286eb5bcc2b53caa894394be589672ccd56f7acfce736c59b52e6b874d9cc60b65e7fbcfa023a561ce562b4878bf7962a8589049', 'สุชานาฎ', 'เกิดนอก', '2621 ข้าวหลาม', 'CM-1', 'COMMISSIONER'),
    ('8167438575289', 'scrypt$795b3127e6ef87f9804b601bc4d4b171$ea7d814c2f88bbfa3999313b286eb5bcc2b53caa894394be589672ccd56f7acfce736c59b52e6b874d9cc60b65e7fbcfa023a561ce562b4878bf7962a8589049', 'พัชรนันท์', 'เกิดค้างพลู', '6 กรุงธนบุรี', 'CM-1', 'COMMISSIONER'),
    ('3656506578750', 'scrypt$795b3127e6ef87f9804b601bc4d4b171$ea7d814c2f88bbfa3999313b286eb5bcc2b53caa894394be589672ccd56f7acfce736c59b52e6b874d9cc60b65e7fbcfa023a561ce562b4878bf7962a8589049', 'สุรษิต', 'เกตุสีสุก', '5385 เลียบวารี', 'CM-1', 'COMMISSIONER'),
    ('5181599500094', 'scrypt$795b3127e6ef87f9804b601bc4d4b171$ea7d814c2f88bbfa3999313b286eb5bcc2b53caa894394be589672ccd56f7acfce736c59b52e6b874d9cc60b65e7fbcfa023a561ce562b4878bf7962a8589049', 'มณทารัตน์', 'แขค้างพลู', '65 ลำไทร', 'CM-1', 'COMMISSIONER');
--rollback DELETE FROM users WHERE national_id IN ('7888165997564','8162104362606','8167438575289','3656506578750','5181599500094');
